// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdEJh8oov5qJl53BjoPuEVOkceXsvKDoU',
    appId: '1:119535848870:web:2237cbbcbc520e4686d367',
    messagingSenderId: '119535848870',
    projectId: 'agriculturescan',
    authDomain: 'agriculturescan.firebaseapp.com',
    storageBucket: 'agriculturescan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ95pmt6BFK_VRqU_iw9BftEXvvlo5Tv0',
    appId: '1:119535848870:android:cab159dd91dc940786d367',
    messagingSenderId: '119535848870',
    projectId: 'agriculturescan',
    storageBucket: 'agriculturescan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGeN1UISQMf2InBBE01bGI7Jq4WQpI9H8',
    appId: '1:119535848870:ios:e40e8eb645b381c686d367',
    messagingSenderId: '119535848870',
    projectId: 'agriculturescan',
    storageBucket: 'agriculturescan.appspot.com',
    androidClientId: '119535848870-41kcv5nf5vf1fj3e5pf0d392qnhl6osv.apps.googleusercontent.com',
    iosClientId: '119535848870-4136b2cnvnhd9fqgrugk5grmfkdbrgui.apps.googleusercontent.com',
    iosBundleId: 'com.thesis.amaff',
  );
}
